### PR TITLE
Synchronous rendering on Metal when annotation views are visible

### LINKED ISSUE #2053: [iOS - Metal - v6.0.0]  - MLNAnnotationView delay with map panning
**Describe the bug**
I've been doing some tests with MapLibre Native iOS (6.0.0 (Metal)) And I was just testing some annotations.
Just wondering if this visible delay of annotation views was already there in 5.x.x or someone has the same behaviour ?
The blue ones are MLNAnnotationImage (UIView converted to Image) and the red ones are MLNAnnotationView.
And as you can see the red ones have a slight delay when panning the map. Just like the user location annotation.

**To Reproduce**
Create a MLNAnnotationView and add it to the map.
```
class TestAnnotationView: MLNAnnotationView {
    init(annotation: MLNAnnotation) {
        super.init(annotation: annotation, reuseIdentifier: "test-identifier")
        frame = CGRect(x: 0, y: 0, width: 40, height: 40)
        layer.cornerRadius = 20
        backgroundColor = .red
    }
}
```

**Expected behavior**
I would expect that the MLNAnnotationView and UserLocationAnnotation has slight to no delay as the MLNAnnotationImage?
MLNAnnotationImage will always have better performance but even with 1 annotation it has slight delay.

**Screenshots**
https://github.com/maplibre/maplibre-native/assets/10544377/d7f309cd-04b9-4e72-8b52-e1a1f3e51813

**Platform information (please complete the following information):**
 - OS: iOS
 - Version 6.0.0

Any help is welcome 🙏

### PR DESCRIPTION
**Pull request by stefankarschti**
Implement conditional synchronous rendering on Metal backend when annotation views are visible, that is waiting for frames to fully complete by invoking `[commandBuffer waitUntilCompleted];` in the `swap` method of the `MLNMapViewMetalRenderableResource`.

This is needed because the map transformation is set as soon as the camera is mutated, and annotations are positioned on the screen according to that in `MLNMapView`::`renderSync` -> `updateAnnotationViews`, while the frame rendering is completing asynchronously on Metal - which causes desynchronization.

ref: #2082 
Fixes #2053

### CODE REVIEW

File: platform/ios/src/MLNMapView+Metal.h [hunk 1]
```diff
@@ -50,6 +50,9 @@ class MLNMapViewMetalImpl final : public MLNMapViewImpl,
     MLNBackendResource getObject() override;
     // End implementation of MLNMapViewImpl
 
+    virtual void setSynchronous(bool value) override { synchronousFrame = value; };
```
Comment (mwilsnd) [inline platform/ios/src/MLNMapView+Metal.h:53]: nit: `virtual` isn't required when the `override` keyword is present, high compiler warning levels can complain if they follow the core guidelines on [virtual, override and final](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines.html#c128-virtual-functions-should-specify-exactly-one-of-virtual-override-or-final)

**Review by mwilsnd — CHANGES_REQUESTED** [review]

**Review by mwilsnd — APPROVED** [review]

**Comment by michaelkirk** [comment]
Thank you so much, it looks much better now! ❤️
